### ISSUE TITLE
How to get the tranformed Image

### ISSUE THREAD

**Issue by ghost** [quqixun/ImageRegistration#1]
How can I get the transformed Image without warping it onto the source image?

**Comment by quqixun** [comment]
> How can I get the transformed Image without warping it onto the source image?

Sorry for so so so late reply.
Perhaps you had solved it.

Actually, I did not get your point very clearly.
The source image has to be wrapped to fit target image.

https://github.com/quqixun/ImageRegistration/blob/master/align_transform.py#L182
**warp** is just the wrapped result.
