### ISSUE TITLE
it stopped

### ISSUE THREAD

**Issue by dzz416** [quqixun/ImageRegistration#4]
After running, only one picture comes out, and then the program seems to enter an infinite loop

**Comment by quqixun** [comment]
Image was shown by cv2.imshow, using q to quit.
I also updated code to run newest opencv, have a try.

**Comment by Afeihhhhh** [comment]
Hello, I would like to have your contact information, I would like to ask you some questions, thank you.

**Comment by dzz416** [comment]
QQ:1781457125
Wechat:17791483344




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "quqixun/ImageRegistration"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月25日(星期五) 晚上9:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [quqixun/ImageRegistration] it stopped (Issue #4)





 
Hello, I would like to have your contact information, I would like to ask you some questions, thank you.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
